export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const LOADING_ROOMS_SUCCESS = 'LOADING_ROOMS_SUCCESS';
export const FETCH_ROOMS_ERROR = 'FETCH_ROOMS_ERROR';
export const RESET_ERROR = 'RESET_ERROR';
export const SELECT_ROOM_SUCCESS = 'SELECT_ROOM_SUCCESS';
export const EDIT_ROOM_SUCCESS = 'EDIT_ROOM_SUCCESS';
export const FILTER_ROOMS_SUCCESS = 'FILTER_ROOMS_SUCCESS';
export const SORT_ROOMS_SUCCESS = 'SORT_ROOMS_SUCCESS';
